In [ ]:
import numpy as np
#creating an array
ar=np.array([45,63,98,56,23,41])
#ar=np.array([45,63,98,56,23,41,'abc'])
print(type(ar))
print(ar)
print(ar.dtype)
print(ar.shape)
print(ar.size)  #no of elements
print(ar.ndim)

<class 'numpy.ndarray'>
[45 63 98 56 23 41]
int64
(6,)
6
1


In [ ]:
#arange(start,stop,step)
ar1=np.arange(1,10)
ar1=np.arange(1,50,2)
print(ar1)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [ ]:
ar=np.array([45,63,98,56,23,41])
print(ar[0])

45


In [ ]:
#2D array
ar3=np.array([[45,63,98],[56,23,41],[78,96,32],[10,20,30]])
print(ar3)
print(ar3.shape) #rows,columns
print(ar3.ndim)
print(ar3.size)

[[45 63 98]
 [56 23 41]
 [78 96 32]
 [10 20 30]]
(4, 3)
2
12


In [ ]:
print(ar3[1][2])

41


In [ ]:
for i in ar3:
    print(i)

[45 63 98]
[56 23 41]
[78 96 32]
[10 20 30]


In [ ]:
for i in np.nditer(ar3):
  print(i)

45
63
98
56
23
41
78
96
32
10
20
30


In [ ]:
#Matrix Multiplication
ar_a=np.array([[1,2,3],[4,5,6]])
ar_b=np.array([[10,11],[20,21],[30,31]])
print(ar_a)
print(ar_b)

[[1 2 3]
 [4 5 6]]
[[10 11]
 [20 21]
 [30 31]]


In [ ]:
ar_mul=np.dot(ar_a,ar_b)
print(ar_mul)

[[140 146]
 [320 335]]


In [ ]:
marks=np.array([45,96,85,67,78,45,90,56,57,97,90,85,84,67])
print("Sum:",marks.sum())
print("Max:",marks.max())
print("Min:",marks.min())
print("Mean:",marks.mean())
print("Median:",np.median(marks))
print("Std:",marks.std())
print("Variance:",marks.var())

Sum: 1042
Max: 97
Min: 45
Mean: 74.42857142857143
Median: 81.0
Std: 17.47125919787076
Variance: 305.2448979591837


In [ ]:
#Broadcasting airthemical operations
lst=[10,20,30]
print(lst*3)

ar4=np.array([10,20,30])
print(ar4*3)

[10, 20, 30, 10, 20, 30, 10, 20, 30]
[30 60 90]


**Pandas**

Reading data

In [ ]:
#Import and Export
#Common filetypes: csv,excel,JSON

#Import Functiond: read_csv(),read_excel(),read_json()
#Export Functiond: to_csv(),to_excel(),to_json()

In [ ]:
import pandas as pd

df=pd.read_csv("/content/Social_Network_Ads.csv")
#df=pd.read_csv("/content/Social_Network_Ads.csv",index_col='User ID')
print(df)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]


In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB
None


In [ ]:
print(df.describe())

            User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000


In [ ]:
print(df.describe(include='object'))

        Gender
count      400
unique       2
top     Female
freq       204


In [ ]:
#Setup custom index
df.set_index('User ID',inplace=True)
print(df)

          Gender  Age  EstimatedSalary  Purchased
User ID                                          
15624510    Male   19            19000          0
15810944    Male   35            20000          0
15668575  Female   26            43000          0
15603246  Female   27            57000          0
15804002    Male   19            76000          0
...          ...  ...              ...        ...
15691863  Female   46            41000          1
15706071    Male   51            23000          1
15654296  Female   50            20000          1
15755018    Male   36            33000          0
15594041  Female   49            36000          1

[400 rows x 4 columns]


Selections: specific columns and rows

In [ ]:
print(df['EstimatedSalary'])

User ID
15624510    19000
15810944    20000
15668575    43000
15603246    57000
15804002    76000
            ...  
15691863    41000
15706071    23000
15654296    20000
15755018    33000
15594041    36000
Name: EstimatedSalary, Length: 400, dtype: int64


In [ ]:
print(df.Age)

User ID
15624510    19
15810944    35
15668575    26
15603246    27
15804002    19
            ..
15691863    46
15706071    51
15654296    50
15755018    36
15594041    49
Name: Age, Length: 400, dtype: int64


In [ ]:
#selecting specific columns
print(df[['Age','EstimatedSalary']])

          Age  EstimatedSalary
User ID                       
15624510   19            19000
15810944   35            20000
15668575   26            43000
15603246   27            57000
15804002   19            76000
...       ...              ...
15691863   46            41000
15706071   51            23000
15654296   50            20000
15755018   36            33000
15594041   49            36000

[400 rows x 2 columns]


In [ ]:
#Label Based: at[],loc[]
#Condition Based:df[condition]

In [ ]:
#at[row_index,column_label]  only one index and one label
print(df.at[15603246,'EstimatedSalary'])

57000


In [ ]:
#Update values
df.at[15603246,'EstimatedSalary']=60000   #new value
print(df)

          Gender  Age  EstimatedSalary  Purchased
User ID                                          
15624510    Male   19            19000          0
15810944    Male   35            20000          0
15668575  Female   26            43000          0
15603246  Female   27            60000          0
15804002    Male   19            76000          0
...          ...  ...              ...        ...
15691863  Female   46            41000          1
15706071    Male   51            23000          1
15654296  Female   50            20000          1
15755018    Male   36            33000          0
15594041  Female   49            36000          1

[400 rows x 4 columns]


In [ ]:
#loc[row_index_range,columns labels]
print(df.loc[15624510:15804002,['Gender','Age','Purchased']])

          Gender  Age  Purchased
User ID                         
15624510    Male   19          0
15810944    Male   35          0
15668575  Female   26          0
15603246  Female   27          0
15804002    Male   19          0


In [ ]:
print(df.loc[15804002])

Gender              Male
Age                   19
EstimatedSalary    76000
Purchased              0
Name: 15804002, dtype: object


In [ ]:
print(df.loc[[15804002,15706071,15810944],['Age','EstimatedSalary']])

          Age  EstimatedSalary
User ID                       
15804002   19            76000
15706071   51            23000
15810944   35            20000


In [ ]:
#Conditional Selections
print(df[df['Age']>50])

          Gender  Age  EstimatedSalary  Purchased
User ID                                          
15605000  Female   59            83000          0
15660866  Female   58           101000          1
15654230  Female   55           130000          1
15794566  Female   52           114000          0
15735878    Male   52           150000          1
15707596  Female   59            42000          0
15779529  Female   60           108000          1
15732987    Male   59           143000          1
15593715    Male   60           102000          1
15685346    Male   56           133000          1
15772073  Female   53           143000          1
15769596  Female   56           104000          1
15722061  Female   51           146000          1
15775590  Female   57           122000          1
15750056  Female   52            90000          1
15569641  Female   58            95000          1
15672821  Female   55           125000          1
15688172  Female   59            76000          1


In [ ]:
#&-and |-or
print(df[(df['Age']>50) & (df['Gender']=='Female') & (df['EstimatedSalary']>100000)])

          Gender  Age  EstimatedSalary  Purchased
User ID                                          
15660866  Female   58           101000          1
15654230  Female   55           130000          1
15794566  Female   52           114000          0
15779529  Female   60           108000          1
15772073  Female   53           143000          1
15769596  Female   56           104000          1
15722061  Female   51           146000          1
15775590  Female   57           122000          1
15672821  Female   55           125000          1
15603942  Female   51           134000          0
15667417  Female   54           104000          1
15774872  Female   52           138000          1
15588080  Female   53           104000          1
15768151  Female   54           108000          1


In [ ]:
df_new=df[(df['Age']>50) & (df['Gender']=='Female') & (df['EstimatedSalary']>100000)]

In [ ]:
print(df_new)

          Gender  Age  EstimatedSalary  Purchased
User ID                                          
15660866  Female   58           101000          1
15654230  Female   55           130000          1
15794566  Female   52           114000          0
15779529  Female   60           108000          1
15772073  Female   53           143000          1
15769596  Female   56           104000          1
15722061  Female   51           146000          1
15775590  Female   57           122000          1
15672821  Female   55           125000          1
15603942  Female   51           134000          0
15667417  Female   54           104000          1
15774872  Female   52           138000          1
15588080  Female   53           104000          1
15768151  Female   54           108000          1


In [ ]:
#Random Sampling/selection
print(df.sample(5))

          Gender  Age  EstimatedSalary  Purchased
User ID                                          
15795298  Female   48           134000          1
15631159    Male   47            20000          1
15610403  Female   28            59000          0
15595135  Female   23            66000          0
15675949  Female   33           149000          1


In [ ]:
#Export Data    DF--->file
df_new.to_excel("Selected_data.xlsx")
df_new.to_json("file1.json")